services: docker
sudo: required
dist: xenial
language: go
go:
  - 1.13.x

env:
  global:
    - OCTOKIT_API_ENDPOINT="https://github.ibm.com/api/v3/"
    - PATH=/opt/python/3.6.7/bin:$PATH
    - GO111MODULE=on
    - KUBE_VERSION="v1.16.2"
    - OP_VER="v0.11.0"
    - CSI_OP_VER="${TRAVIS_BRANCH}.${TRAVIS_OS_NAME}"
    - QUAY_USERNAME="mew2057"
    - DOCKER_REPO="quay.io/${QUAY_USERNAME}/ibm-spectrum-scale-csi-operator-test:${CSI_OP_VER}"
    - LOCAL_IMAGE="csi.ibm.com/csi-scale-operator:testing"

    - OPERATOR_SDK="https://github.com/operator-framework/operator-sdk/releases/download/${OP_VER}/operator-sdk-${OP_VER}-x86_64-linux-gnu"
    - CSI_OP_BUILD_DIR="${TRAVIS_BUILD_DIR}/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator"


    - OPERATOR_NAME=ibm-spectrum-scale-csi-operator
    - OLM_MANIFEST="${CSI_OP_BUILD_DIR}/deploy/olm-catalog/${OPERATOR_NAME}/"

    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

addons:
  apt:
    packages:
      - "python3"
      - "python3-dev"
      - "python3-pip" 
stages:
  - lint
  - build
  - test
jobs:
  fast_finish: true
  include:
    
    # Install operator-courier and run the lint on the manifest.
    - stage: lint
      name: "Lint: Run linters and bundle automation."
      script:
        - pip install ansible
        # Testing that the generated files match the deploy/*.yaml files, it they do not match, fail Travis
        - ansible-playbook ${TRAVIS_BUILD_DIR}/tools/ansible/generate-playbook.yaml --extra-vars "travis_testing=true"
        - pip install operator-courier
        - cd ${CSI_OP_BUILD_DIR}
        - python hacks/package_operator.py -d ${OLM_MANIFEST}  -o /tmp/operator --nozip 
        - operator-courier --verbose verify --ui_validate_io /tmp/operator

    - name: "Lint: CASE"
      if: env.HELM_REPO_SSH_LOCATION!=""
      before_install:
        - if [[  -z "$HELM_REPO_SSH_LOCATION" ]] ; then exit 0;fi
      install:
        # Clone build tools & set tools path for follow on processing
        # The clone command will use the ssh key from the travis settings to clone the repo from github.ibm.com
        - if [[  -z "$HELM_REPO_SSH_LOCATION" ]] ; then exit 0;fi
        - if [[ ! -z "$BRANCH_OVERRIDE" ]] ; then
            git clone -b $BRANCH_OVERRIDE git@github.ibm.com:ibmprivatecloud/content-tools;
          else
            git clone git@github.ibm.com:ibmprivatecloud/content-tools;
          fi
        - export toolsPath=`pwd`/content-tools/travis-tools/
        # Install dependencies & determine chart delta
        - $toolsPath/build/bin/installDependencies.sh
        - export changeList=`$toolsPath/build/bin/determineChartDelta.sh | tee determineChartDelta.out | grep 'return determineChartDelta:' | cut -f2 -d:` && cat determineChartDelta.out
        # Package for release
        - if [[ ! -z "$TRAVIS_TAG" ]] ; then $toolsPath/release/bin/package.sh; fi
        # Lint and install/test charts (if cv-tests exist)
        - $toolsPath/cv-test/bin/validateContent.sh
      deploy:
          # scp helm repo(s) to location identified (Note: SSHPASS env variable must contain password)
          - provider: script
            skip_cleanup: true
            script:  $toolsPath/build/bin/deployHelmRepo.sh
            on:
              all_branches: true
          # Publish tagged release
          - provider: releases
            skip_cleanup: true
            api_key: $GITHUB_TOKEN
            file_glob: true
            file: repo/stable/*
            on:
              tags: true
       


    - stage: build
      name: "Build: operator"
      script:
        - sudo pip install docker
        - docker version
        - ${TRAVIS_BUILD_DIR}/tools/scripts/ci/install_operator-sdk.sh
        - cd ${CSI_OP_BUILD_DIR}
        - operator-sdk version
        - go version
        - operator-sdk build csi-scale-operator
        - docker tag csi-scale-operator ${DOCKER_REPO}
          #- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin  quay.io; docker push ${DOCKER_REPO}; fi'

    - name: "Build: docs"
      script:
        - pip install sphinx sphinx_rtd_theme recommonmark 
        - cd ${TRAVIS_BUILD_DIR}/docs
        - make html


    # Install minikube, build the image and run the scorecard.
    - stage: test
      name: "Test: scorecard"
      before_install:
        - sudo pip install docker
        - pip install openshift
        - ${TRAVIS_BUILD_DIR}/tools/scripts/ci/install_minikube.sh
        - ${TRAVIS_BUILD_DIR}/tools/scripts/ci/install_operator-sdk.sh
        - kubectl version
        - cd ${CSI_OP_BUILD_DIR}
        - eval $(minikube docker-env) # Popping this out, because I don't think the script is working.
        - operator-sdk build csi-scale-operator
        - docker tag csi-scale-operator ${DOCKER_REPO}
      script: 
        # Print environment 
        # Build the image, clear and restore the finalizers.
        - python hacks/clear_finalizers.py
        - python hacks/change_deploy_image.py -i ${DOCKER_REPO} --ifnotpresent
        - kubectl create -f deploy/namespace.yaml
        - operator-sdk scorecard --config .osdk-scorecard.yaml
        - python  hacks/clear_finalizers.py --restore
        
    - before_install:
        - sudo pip install docker
        - pip install pyyaml molecule openshift docker jmespath kubernetes-validate
        - ${TRAVIS_BUILD_DIR}/tools/scripts/ci/install_minikube.sh
        - ${TRAVIS_BUILD_DIR}/tools/scripts/ci/install_operator-sdk.sh
        - kubectl version
        - cd ${CSI_OP_BUILD_DIR}
        - eval $(minikube docker-env) # Popping this out, because I don't think the script is working.
        - operator-sdk build csi-scale-operator
        - docker tag csi-scale-operator ${LOCAL_IMAGE}
      name: "Test: molecule"
      script: 
        #  This needs to be built before we can test with molecule for reasons.
        - python hacks/change_deploy_image.py -i ${LOCAL_IMAGE} --ifnotpresent
        - kubectl create -f deploy/namespace.yaml
        - molecule test -s test-local

          #- ${TRAVIS_BUILD_DIR}/tools/scripts/ci/fold_ouput.sh cluster.info.2 "cluster information"  kubectl cluster-info dump
notifications:
  email: false
