# spectrum_scale.yaml
apiVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata:
    name: 'ibm-spectrum-scale-csi'
    namespace: ibm-spectrum-scale-csi-driver
status: {}
spec:
  # Required
  # ----
  # The path to the gpfs file system mounted on the host machine.
  scaleHostpath: "< GPFS FileSystem Path >"

  # A collection of gpfs cluster properties for the csi driver to mount.
  clusters:
    # The cluster id of the gpfs cluster specified (mandatory).
    - id: "< Primary Cluster ID >"

      # A string specifying a secret resource name.
      secrets: "< Primary Cluster Secret >"

      # Require a secure SSL connection to connect to GPFS.
      secureSslMode: false

      # A string specifying a cacert resource name.
      # cacert: <>

      # The primary file system for the GPFS cluster
      primary:
        # The name of the primary filesystem.
        primaryFs: "< Primary Filesystem >"
        # The name of the primary fileset, created in primaryFS.
        primaryFset: "< Fileset in Primary Filesystem >"

      # A collection of targets for REST calls.
      restApi:
        # The hostname of the REST server.
        - guiHost: "< Primary cluster GUI IP/Hostname >"

          # The port number running the REST server.
          # guiPort
  # ----
