# spectrum_scale.yaml
apiVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata:
    # IMPORTANT THE OPERATOR LOOKS FOR THIS!
    name: 'ibm-spectrum-scale-csi'
    namespace: ibm-spectrum-scale-csi-driver
status: {}
spec:
  # ----
  # Attacher image for csi (actually attaches to the storage).
  attacher: "quay.io/k8scsi/csi-attacher:v1.0.0"

  # Provisioner image for csi (actually issues provision requests).
  provisioner: "quay.io/k8scsi/csi-provisioner:v1.0.0"

  # Sidecar container image for the csi spectrum scale plugin pods.
  driverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v1.0.1"

  # Image name for the csi spectrum scale plugin container.
  spectrumScale: "quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v0.9.1"
  # ----

  # Required
  # ----
  # The path to the gpfs file system mounted on the host machine.
  scaleHostpath: "<REPLACE ME>"

  # A collection of gpfs cluster properties for the csi driver to mount.
  clusters:
    # The cluster id of the gpfs cluster specified (mandatory).
    - id: "<REPLACE ME>"

      # A string specifying a secret resource name.
      secrets: "<REPLACE ME>"

      # Require a secure SSL connection to connect to GPFS.
      secureSslMode: false

      # A string specifying a cacert resource name.
      # cacert: <>

      # The primary file system for the GPFS cluster
      primary:
        # The name of the primary filesystem.
        primaryFS: "<REPLACE ME>"
        # The name of the primary fileset, created in primaryFS.
        primaryFset: "<REPLACE ME>"

      # A collection of targets for REST calls.
      restApi:
        # The hostname of the REST server.
        - guiHost: "<REPLACE ME>"

          # The port number running the REST server.
          # guiPort

  # ----
