apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ssco-ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-csi-operator-role
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-operator-sa
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ssco-csi-nodeplugin
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-node-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-csi-node-role
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-node-sa
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ssco-external-provisioner-runner
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-csi-provisioner-role
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-provisioner-sa
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ssco-external-attacher-runner
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
  name: ibm-spectrum-scale-csi-attacher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-csi-attacher-role
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-attacher-sa
  namespace: ibm-spectrum-scale-csi-driver
