- name: "Write the updated package"
  template: 
    src: "ibm-spectrum-scale-csi-operator.package.yaml.j2"
    dest: "~/demo/ibm-spectrum-scale-csi-operator.package.yaml"

# TODO does a module do this?
- name: "Get Registry version and increment"
  shell: "helm registry list quay.io -o {{ QUAY_NAMESPACE }} --output json "
  register: registry_out

- set_fact:
    registry: "{{ registry_out.stdout  | from_json }}"
- set_fact:
    maj: "{{ registry[0].releases[0].split('.')[0]  }}"
    min: "{{ registry[0].releases[0].split('.')[1]  }}"
    ptf: "{{ registry[0].releases[0].split('.')[2] | int + 1 }}"
- set_fact:
    nver: "{{maj}}.{{min}}.{{ptf}}"

# TODO need to hide  password somehow.
- name: "Login to Quay"
  uri:
    url: https://quay.io/cnr/api/v1/users/login
    method: "POST"
    body_format: json
    body:
      user:
        username: "{{QUAY_USERNAME}}"
        password: "{{QUAY_PASSWORD}}"
    return_content: yes
  register: login
- set_fact:
    ltok: "{{ login.json.token }}"

- name: "Push operator to quay"
  shell:  'operator-courier  push "{{OPERATOR_DIR}}" "{{QUAY_NAMESPACE}}" "{{PACKAGE_NAME}}" "{{nver}}" "{{ltok}}"'

- name: "Patch the operator source status to {} to pull the latest"
  shell: "kubectl patch operatorsource -n {{NAMESPACE}} ibm-spectrum-scale-csi -p '[{\"op\":\"replace\",\"path\":\"/status\",\"value\":{}}]'  --type json"

- pause:
    prompt: "OLM configured to use {{item}}, press any key to continue"
    echo: no
  when: INTERACTABLE
