---

- name: "delete the directory {{ generated_dir }}"
  file:
    path: "{{ generated_dir }}"
    state: absent
  when: not testing

- name: "create the directory {{ generated_dir }}"
  file:
    path: "{{ generated_dir }}"
    state: directory
    mode: '0755'

- name: "Combining the individual deploy/*yaml files into a single one: {{ generated_op_yaml }}"
  blockinfile:
    marker: "# {mark} {{ item.name }}"
    dest: "{{ generated_op_yaml }}"
    block: "{{ lookup('file', '{{ operator_dir }}/{{ item.name }}') }}"
    state: present
    create: yes
  with_items:
    - "{{ operator_files }}"

- name: copy over the files that are not modified
  copy:
    src: "{{ operator_dir }}/{{ item }}"
    dest: "{{ generated_dir }}"
  with_items: 
    - "deploy/namespace.yaml"
    - "example/spectrum_scale.yaml"
  when: non_generated

- name: "[Testing] Comparing the generated operator file with checked in code ..."
  shell: "diff {{ generated_dir }}/ibm-spectrum-scale-csi-operator.test.yaml {{ generated_dir }}/ibm-spectrum-scale-csi-operator.yaml"
  failed_when: "diff_output.rc != 0"
  register: diff_output
  when: testing
