apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default 
data:
  # Key value corresponds to a user name defined in ceph cluster
  admin: YWRtaW4=
  # Key value corresponds to a user name defined in ceph cluster
  kubernetes: a3ViZXJuZXRlcw==
