apiVersion: csi.ibm.com/v1
kind: CSIScaleOperator
metadata:
  app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
  app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
  app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi
  namespace: ibm-spectrum-scale-csi-driver
  release: ibm-spectrum-scale-csi-operator
spec:
  clusters:
  - id: < Primary Cluster ID >
    primary:
      primaryFs: < Primary Filesystem >
      primaryFset: < Fileset in Primary Filesystem >
    restApi:
    - guiHost: < Primary cluster GUI IP/Hostname >
    secrets: secret1
    secureSslMode: false
  scaleHostpath: < GPFS FileSystem Path >
status: {}
