--- 
- name: Process Secret
  become: no
  hosts: all
  gather_facts: false
  vars:
    LABEL: app.kubernetes.io/name
    LABEL_VALUE: ibm-spectrum-scale-csi-operator 
  tasks:
  - debug:
      msg:
        - "meta - {{ __secret.metadata  }}"

  - name: Verify this is a labeled secret.
    meta: end_play
    when: __secret.metadata.labels is not defined  or
      __secret.metadata.labels["app.kubernetes.io/name"] is not defined or
      __secret.metadata.labels["app.kubernetes.io/name"]  != "ibm-spectrum-scale-csi-operator"

  - name: Get Scale operators in namespace
    k8s_info:
      kind: CSIScaleOperator
      namespace: "{{ __secret.metadata.namespace }}"
    register: results

  - name: Bump the secret counter for resources with the secret.
    k8s:
      state:  present
      definition:
        apiVersion: "{{item.apiVersion}}"
        kind: "CSIScaleOperator"
        metadata: 
          name: "{{item.metadata.name}}"
          namespace: "{{meta.namespace}}"
        data: 
          spec:
            secretCounter: "{{item.spec.secretCounter}} + 1"
    when: "__secret.metadata.name in (item | json_query('spec.clusters[*].secrets') )"
    loop: "{{results.resources}}"

