- name: Dynamically Generate Installer Files
  hosts: localhost
  gather_facts: false

  vars:
    repo_root_dir: "{{ playbook_dir }}/../"
    operator_dir: "{{ repo_root_dir }}/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator"

    generated_dir: "{{ repo_root_dir }}/generated/installer"
    generated_op_yaml: "{{ generated_dir }}/ibm-spectrum-scale-csi-operator.yaml"
    operator_files: 
      - name: "deploy/operator.yaml"
      - name: "deploy/role.yaml"
      - name: "deploy/role_binding.yaml"
      - name: "deploy/service_account.yaml"
      - name: "deploy/crds/ibm_v1alpha1_csiscaleoperator_crd.yaml"

    # Copy over the non modified file to the installer directory
    non_generated: false
    
  tasks:
    - name: Create files to help manually install the operator
      include_tasks: generate/create_files.yaml
