scorecard:
  init-timeout: 120
  output: json
  plugins:
    - basic:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
            - "deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml"
    - olm:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
            - "deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.0.1/ibm-spectrum-scale-csi-operator.v1.0.1.clusterserviceversion.yaml"
# TODO add custom test.


